---
all:
  children:
    app_servers:
      hosts:
        app01:
          ansible_host: 1.201.116.156
        app02:
          ansible_host: 1.201.117.194
        app03:
          ansible_host: 1.201.116.180
        app04:
          ansible_host: 1.201.118.202
        app05:
          ansible_host: 1.201.118.10
        app06:
          ansible_host: 1.201.118.90
    rolling_targets:
      hosts:
        app01:
        app02:
        app03:
